name: retail_customer_analytics
version: "1.0.0"
config-version: 2
profile: retail_customer_analytics

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retail_customer_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
